apiVersion: 1

datasources:
  - name: CloudWatch
    uid: cloudwatch
    type: cloudwatch
    access: proxy
    isDefault: true
    jsonData:
      authType: default
      defaultRegion: us-east-1
      assumeRoleArn: ""
      externalId: ""
      customMetricsNamespaces: ""
